apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: prometheus-smartctl-exporter
    version: 0.13.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: smartctl-exporter
    namespace: monitoring
    valuesFile: values.yaml
resources:
  - prometheusrule.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: smartctl-exporter-namespace
      namespace: monitoring
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true
