apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  groups:
    - name: smartctl-exporter.rules
      rules:
        - alert: SmartCTLDeviceMediaErrors
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} has media errors
          expr: smartctl_device_media_errors != 0
          for: 5m
          labels:
            severity: critical
        - alert: SmartCTLDeviceCriticalWarning
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} has critical warning
          expr: smartctl_device_critical_warning != 0
          for: 5m
          labels:
            severity: critical
        - alert: SmartCTLDeviceAvailableSpareUnderThreshold
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} is under available
              spare threshold
          expr: smartctl_device_available_spare_threshold > smartctl_device_available_spare
          for: 1m
          labels:
            severity: critical
        - alert: SmartCTLDeviceStatus
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} has a bad status
          expr: smartctl_device_status != 1
          for: 5m
          labels:
            severity: critical
        - alert: SmartCTLDInterfaceSlow
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} interface is slower
              than it should be
          expr: >-
            smartctl_device_interface_speed{speed_type="current"} != on(device, instance, namespace,
            pod) smartctl_device_interface_speed{speed_type="max"}
          for: 5m
          labels:
            severity: critical
        - alert: SmartCTLDDeviceTemperature
          annotations:
            summary: >-
              Device {{ $labels.device }} on instance {{ $labels.instance }} has temperature higher
              than 60°C
          expr: smartctl_device_temperature{temperature_type="current"} > 60
          for: 5m
          labels:
            severity: critical
