apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: tuppr
    version: 0.3.0
    repo: oci://ghcr.io/home-operations/charts
    releaseName: tuppr
    namespace: system
    valuesFile: values.yaml
resources:
  - upgrades
