apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: global-headers
  namespace: networking
spec:
  headers:
    customResponseHeaders:
      server: cool
      # TODO strict-transport-security: max-age=15552000; includeSubDomains; preload
