configOverride: |
  [global]
  bdev_enable_discard = true
  bdev_async_discard = true
  osd_class_update_on_start = false
monitoring:
  enabled: true
  createPrometheusRules: true
cephClusterSpec:
  # TODO remove
  mon:
    count: 1
  mgr:
    count: 1
  resources:
    mgr:
      limits:
        memory: "1Gi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    mon:
      limits:
        memory: "2Gi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    osd:
      limits:
        memory: "4Gi"
      requests:
        cpu: "50m"
        memory: "100Mi"
  # END TODO
  dashboard:
    ssl: false
  network:
    connections:
      requireMsgr2: true
    provider: host
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: sdb
    config:
      osdsPerDevice: "1"
ingress:
  dashboard:
    ingressClassName: traefik
    host:
      name: ceph.chamburr.xyz
      path: /
cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
      replicated:
        # TODO size: 2
        size: 1
        requireSafeReplicaSize: false
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4
cephFileSystems: []
cephBlockPoolsVolumeSnapshotClass:
  enabled: true
  name: ceph-block
  isDefault: true
  deletionPolicy: Delete
cephObjectStores: []
