apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: security
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: /security/vaultwarden
