controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/librespeed/speedtest
          tag: 6.2.0
        env:
          MODE: standalone
          USE_NEW_DESIGN: true
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8080
ingress:
  main:
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: >-
        networking-global-internal-only@kubernetescrd
    hosts:
      - host: speedtest.chamburr.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
