apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    version: 3.7.1
    repo: https://bjw-s.github.io/helm-charts
    releaseName: netmaker-mqtt
    namespace: networking
    valuesFile: values.yaml
configMapGenerator:
  - name: netmaker-mqtt
    files:
      - resources/mosquitto.conf
      - resources/wait.sh
    options:
      disableNameSuffixHash: true
