controllers:
  main:
    containers:
      main:
        image:
          repository: public.ecr.aws/docker/library/redis
          tag: 7.4.2-alpine
        args:
          - redis-server
          - --require-pass
          - ${PASSWORD}
        env:
          PASSWORD:
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: redis-password
    annotations:
      reloader.stakater.com/auto: "true"
service:
  main:
    controller: main
    ports:
      http:
        port: 6379
persistence:
  data:
    existingClaim: nextcloud-redis
    globalMounts:
      - path: /data
