apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wg-easy
  namespace: security
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    template:
      data:
        password: "{{ .password }}"
        __password-hash: "{{ bcrypt .password }}"
  dataFrom:
    - extract:
        key: /security/wg-easy
