apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard
  namespace: networking
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      data:
        password: "{{ .password }}"
        __password-hash: "{{ bcrypt .password }}"
  dataFrom:
    - extract:
        key: /networking/wireguard
