apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    version: 3.7.1
    repo: https://bjw-s.github.io/helm-charts
    releaseName: tailscale
    namespace: networking
    valuesFile: values.yaml
configMapGenerator:
  - name: tailscale
    files:
      - resources/config.yml
    options:
      disableNameSuffixHash: true
resources:
  - ingress
  - pvc.yaml
  - rbac.yaml
  - secret.yaml
