apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
