- name: Install firewall package
  ansible.builtin.package:
    name: ufw
    state: present

- name: Configure firewall services
  community.general.ufw:
    rule: "{{ item.value }}"
    port: "{{ item.key.split('/')[0] }}"
    proto: "{{ item.key.split('/')[1] }}"
  with_dict: "{{ network_firewall_services }}"

- name: Delete firewall services
  community.general.ufw:
    delete: true
    rule: allow
    port: 22
    proto: any

- name: Enable firewall
  community.general.ufw:
    state: enabled

- name: Enable firewall service
  ansible.builtin.service:
    name: ufw
    enabled: true
    state: started
