controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/gravitl/netmaker
          tag: v0.30.0
        env:
          STUN_LIST: stun1.l.google.com:19302,stun2.l.google.com:19302
          BROKER_ENDPOINT: wss://netmaker-mqtt.chamburr.xyz
          SERVER_NAME: chamburr.xyz
          SERVER_API_CONN_STRING: netmaker-api.chamburr.xyz:443
          SERVER_HTTP_HOST: netmaker-api.chamburr.xyz
          SERVER_BROKER_ENDPOINT: ws://netmaker-mqtt.networking:1883
          K8S: true
          TELEMETRY: "off"
          MASTER_KEY:
            valueFrom:
              secretKeyRef:
                name: netmaker-secret
                key: secret
          MQ_USERNAME:
            valueFrom:
              secretKeyRef:
                name: netmaker-secret
                key: username
          MQ_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: netmaker-secret
                key: password
service:
  main:
    controller: main
    ports:
      http:
        port: 8081
ingress:
  main:
    className: traefik
    hosts:
      - host: netmaker-api.chamburr.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
persistence:
  data:
    existingClaim: netmaker
    globalMounts:
      - path: /root/data
