apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: samba-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.123.3
    path: /samba
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: samba-nfs
