injector:
  enabled: false
server:
  updateStrategyType: RollingUpdate
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: vault.chamburr.xyz
        paths:
          - /
  readinessProbe:
    path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
  livenessProbe:
    enabled: true
  postStart:
    - /bin/sh
    - /vault/scripts/init.sh
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: vault
    - name: scripts
      configMap:
        name: vault-scripts
  volumeMounts:
    - name: data
      mountPath: /vault/data
    - name: scripts
      mountPath: /vault/scripts
  dataStorage:
    enabled: false
  standalone:
    config: |-
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }
      storage "file" {
        path = "/vault/data"
      }
ui:
  enabled: true
serverTelemetry:
  serviceMonitor:
    enabled: true
