apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ipsec-vpn
  namespace: security
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      data:
        psk: "{{ .psk }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: /security/ipsec-vpn
