auth:
  - user: ${USERNAME}
    group: ${USERNAME}
    uid: 501
    gid: 501
    password: ${PASSWORD}
global:
  - "force user = root"
  - "force group = root"
share:
  - name: ${USERNAME}
    path: /share/samba
    browsable: yes
    readonly: no
    guestok: no
    validusers: ${USERNAME}
    writelist: ${USERNAME}
    veto: no
